name: Run Tests

on: [workflow_dispatch]

jobs:
  test-my-code:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run my test script
        run: npm test
